# pull official base image
FROM python:3.9.1

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt


# RUN useradd -ms /bin/bash app

# USER app
WORKDIR /home/app



# copy project
COPY . .